---

- name: nvidia-runtime-containerd release key is registered
  apt_key:
    url: https://nvidia.github.io/nvidia-container-runtime/gpgkey
    state: present

- name: software-properties-common is installed for prerequisite for apt_repository ansible module
  apt:
    name: software-properties-common
    state: present
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"

- name: nvidia-container-runtime apt repositories are registered
  apt_repository:
    repo: "{{ item }}"
    filename: nvidia-container-runtime
    state: present
    mode: 0644
    update_cache: "{{ 'yes' if not ansible_check_mode | bool else 'no' }}"
  with_items:
    - 'deb https://nvidia.github.io/libnvidia-container/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/amd64 /'
    - 'deb https://nvidia.github.io/nvidia-container-runtime/{{ ansible_distribution | lower }}{{ ansible_distribution_version }}/amd64 /'
  register: nvidia_container_runtime_apt_repo

- set_fact:
    nvidia_container_runtime_apt_repo_exists: "{{ nvidia_container_runtime_apt_repo_exists|default(true) and item.changed }}"
  with_items:
    nvidia_container_runtime_apt_repo.results

- name: nvidia-container-runtime is installed
  apt:
    name: "nvidia-container-runtime={{ nvidia_container_runtime_specific_version | regex_search('([^*]*)') }}*"
    state: present
  when: not ansible_check_mode or nvidia_container_runtime_apt_repo_exists
